In [23]:
#Exercise sheet 01
#Import libs
import numpy as np
import matplotlib.pyplot as plot

In [24]:
#Exercise 1
#a)

#Transformation of coordinate in local vehicle coordinate system to global coordinate system

#Movement of global origin to local origin:
#Rotation       +90 °
#Translation    [0,1]   from global perspective

x1_p1 = np.array([[ 2],
                  [-2],
                  [ 1]])
x1_theta = np.deg2rad(90)

g_x = 0
g_y = 1

g_T_x1 = np.array([[np.cos(x1_theta), -np.sin(x1_theta), g_x],
                   [np.sin(x1_theta),  np.cos(x1_theta), g_y],
                   [0,                 0,                1  ]])

g_p1 = g_T_x1.dot(x1_p1)

print('Transform x1 to g:')
print(g_p1)

Transform x1 to g:
[[2.]
 [3.]
 [1.]]


In [25]:
#Exercise 1
#b
#Version 1 via inverse Matrix
#Movement of local origin to global origin:
#Rotation       -90 °
#Translation    [-1,0]   from local perspective

#From previous part:
# g_p1 = g_T_x1 * x1_p1
# x1_p1 = inverse(g_T_x1) * g_p1

#Inverse of matrix exists if it's determinant != 0
det_T = np.linalg.det(g_T_x1)
if det_T != 0:
    print("Determinant is != 0")
    print(det_T)

inv_g_T_x1 = np.linalg.inv(g_T_x1)
print("Inverse of T:")
print(inv_g_T_x1)

#Calculate point from global to local
g_p1 = np.array([[2],
                [3],
                [1]])
x1_p1 = inv_g_T_x1.dot(g_p)

print("x1_p1:")
print(x1_p1)

Determinant is != 0
1.0
Inverse of T:
[[ 6.123234e-17  1.000000e+00 -1.000000e+00]
 [-1.000000e+00  6.123234e-17 -6.123234e-17]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
x1_p1:
[[ 2.]
 [-2.]
 [ 1.]]


In [26]:
#Exercise 1
#b
#Version 1 via inverse Matrix
#Movement of local origin to global origin:
#Rotation       -90 °
#Translation    [-1,0]   from local perspective

g_p1 = np.array([[2],
                [3],
                [1]])

g_theta = np.deg2rad(-90)

x1_x = -1
x1_y = 0

x1_T_g = np.array([[np.cos(g_theta), -np.sin(g_theta), x1_x],
                   [np.sin(g_theta),  np.cos(g_theta), x1_y],
                   [0,                0,               1   ]])

x1_p1 = x1_T_g.dot(g_p1)

print(x1_T_g)

print('Transform g to x1:')
print(x1_p1)

[[ 6.123234e-17  1.000000e+00 -1.000000e+00]
 [-1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
Transform g to x1:
[[ 2.]
 [-2.]
 [ 1.]]


In [18]:
#Exercise 1
#c
#Robot moves to new location x2
#Manual check of x1_T_x2

x2_theta = np.deg2rad(180)

x1_x = -2
x1_y = 1

x1_T_x2 = np.array([[np.cos(x2_theta),  -np.sin(x2_theta),  x1_x],
                    [np.sin(x2_theta),   np.cos(x2_theta),  x1_y],
                    [0,                  0,                 1   ]])
print(x1_T_x2)

[[-1.0000000e+00 -1.2246468e-16 -2.0000000e+00]
 [ 1.2246468e-16 -1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [28]:
#Exercise 1
#c
#Robot moves to new location x2
#Transformation matrix as combination of Transformation product
print(x1_T_g)

#Thetha of x2 w.r.t. g
x2_theta = np.deg2rad(-90)
g_x = -1
g_y = -1

g_T_x2 = np.array([[np.cos(x2_theta),  -np.sin(x2_theta),  g_x],
                   [np.sin(x2_theta),   np.cos(x2_theta),  g_y],
                   [0,                  0,                 1  ]])

x1_T_x2 = x1_T_g.dot(g_T_x2)

print(x1_T_x2)

[[ 6.123234e-17  1.000000e+00 -1.000000e+00]
 [-1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
[[-1.0000000e+00  1.2246468e-16 -2.0000000e+00]
 [-1.2246468e-16 -1.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [31]:
#Exercise 1
#d
#Robot is at position x2
#Where is the landmark p1 w.r.t. x2 -> x2_p1?

print(x1_p1)

x2_T_x1 = np.linalg.inv(x1_T_x2)

x2_p1 = x2_T_x1.dot(x1_p1)

print(x2_p1)


[[ 2.]
 [-2.]
 [ 1.]]
[[-4.]
 [ 3.]
 [ 1.]]


In [41]:
#Exercise 1
#d
#Concatenation of multiple Transformations

#x2_T_x1 * x1_T_g * g_p1 = x2_p1

x1_T_g = np.array([[np.cos(np.deg2rad(-90)),  -np.sin(np.deg2rad(-90)), -1],
                   [np.sin(np.deg2rad(-90)),   np.cos(np.deg2rad(-90)),  0],
                   [0,                         0,                        1]])

x2_T_x1 = np.array([[np.cos(np.deg2rad(-180)),  -np.sin(np.deg2rad(-180)), -2],
                    [np.sin(np.deg2rad(-180)),   np.cos(np.deg2rad(-180)),  1],
                    [0,                         0,                          1]])

g_p1 = np.array([[2],
                 [3],
                 [1]])

x2_p1 = x2_T_x1.dot(x1_T_g.dot(g_p1))

print(x2_p1)


[[-4.]
 [ 3.]
 [ 1.]]
