In [13]:
#Include all libraries
import numpy as np
import matplotlib.pyplot as plt

In [8]:
a = np.array([[1,1],
              [1,1]])
b = np.array([[2,0],
              [0,2]])
a.dot
print(a.dot(b))

[[2 2]
 [2 2]]


In [9]:
a = np.array([[1, 0]])
print(a)
b = np.transpose(a)
print(b)

[[1 0]]
[[1]
 [0]]


In [4]:
#Testing affine matrix transformation
x = 2
y = -2

p1 = np.array([[x,y,1]]).transpose()

delta_x = 0
delta_y = 1
theta = np.deg2rad(90)

t = np.array([ [np.cos(theta),   -np.sin(theta),   delta_x],
               [np.sin(theta),    np.cos(theta),   delta_y],
               [0,                0,               1      ]])
p2 = t.dot(p1)

print(p1)
print(p2)

[[ 2]
 [-2]
 [ 1]]
[[2.]
 [3.]
 [1.]]


In [12]:
#Testing affine matrix transformation
x = 2
y = -2

p1 = np.array([[x,y,1]]).transpose()

delta_x = 1
delta_y = 0
theta = np.deg2rad(90)

rt = np.array([[np.cos(theta),   -np.sin(theta),   0],
               [np.sin(theta),    np.cos(theta),   0],
               [0,                0,               1]])

tr = np.array([[1, 0, delta_x],
               [0, 1, delta_y],
               [0, 0, 1      ]])

p2 = rt.dot(tr).dot(p1)

print(p1)
print(p2)

[[ 2]
 [-2]
 [ 1]]
[[2.]
 [3.]
 [1.]]
