In [1]:
#Include all libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Instructions for testing
#1. Plot a point in vehicle coordinate system at position (15,6)
#   Project it to the plane with w = 10

# #Create the Transformation matrix to project the points from plane(w=1) to plane(w=10)
# im_T_v = np.array([[wm_res, 0,          0],
#                    [0,      wm_res,     0],
#                    [0,      0,     wm_res]])

# print(im_T_v)
# print(np.linalg.inv(im_T_v))

# #Create a point v_p01
# v_p01 = np.array([[14.9,5.9,1]])
# v_p01 = np.transpose(v_p01)

# im_p01 = np.dot(im_T_v,v_p01)
# # im_p01 = v_p01 * wm_res
# print(im_p01)

In [3]:
#Given simplified parameters
v_dim_x = np.array([15,-5])
v_dim_y = np.array([6,-6])

wm_res = 10
iTv_theta = np.deg2rad(90)
iTv_deltax = 6      #[m]    Translation has to be done for w = 1 first; projection follows afterwards
iTv_deltay = 15     #[m]    

#Create the Transformation matrix to project the points from plane(w=1) to plane(w=10)
#To Transform from vehicle to image move inside plane w = 1 first
iTv_zoom = np.array([[wm_res, 0,          0],
                     [0,      wm_res,     0],
                     [0,      0,     wm_res]])
iTv_mirror = np.array([[1,  0,   0],
                       [0, -1,   0],
                       [0,  0,   1]])
iTv_rot = np.array([[np.cos(iTv_theta),    -np.sin(iTv_theta),  0],
                    [np.sin(iTv_theta),     np.cos(iTv_theta),  0],
                    [0,                     0,                  1]])
iTv_trans = np.array([[1, 0, iTv_deltax],
                      [0, 1, iTv_deltay],
                      [0, 0,          1]])

# im_T_v = iTv_zoom.dot(iTv_trans.dot(iTv_rot.dot(iTv_mirror)))
im_T_v = iTv_zoom.dot(iTv_trans.dot(iTv_mirror.dot(iTv_rot)))

#Create a point v_p01
v_p01 = np.array([[-5,0,1]])
v_p01 = np.transpose(v_p01)

im_p01 = np.dot(im_T_v,v_p01)
# im_p01 = v_p01 * wm_res
print(im_p01)

[[ 60.]
 [200.]
 [ 10.]]


In [4]:
#Backtransform
im_p03 = np.array([[120],
                   [200],
                    [10]])

v_T_im = np.linalg.inv(im_T_v)

v_p03 = v_T_im.dot(im_p03)

print(v_p03)

[[-5.]
 [-6.]
 [ 1.]]


In [7]:
T = np.array([[ 25, 5,  1],
              [ 64, 8,  1],
              [144, 12, 1]])
print(np.linalg.det(T))
print(np.linalg.inv(T))

-83.99999999999999
[[ 0.04761905 -0.08333333  0.03571429]
 [-0.95238095  1.41666667 -0.46428571]
 [ 4.57142857 -5.          1.42857143]]
